//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int AutoID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Magazine { get; set; }
        public short Article_Category { get; set; }
        public short Article_Status { get; set; }
        public string Thumbnail_Name { get; set; }
        public string Video_Name { get; set; }
        public string Content_Name { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Article_Category Article_Category1 { get; set; }
        public virtual Article_Status Article_Status1 { get; set; }
        public virtual Magazine Magazine1 { get; set; }
    }
}
